### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by geoidesic** [vanbosse/rabbitmq-demo#1]
Don't know if there is a better place for this question.

I'm trying your example and installation instructions on a mac running Yosemite and MAMP pro. Getting this error when trying to run "node js/server.js":

```
node js/server.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

Firewall is disabled, so all ports are open. MAMP is running on port 80. Browsing to localhost:8080 gives a 404, so presumably there's nothing else listening on the port.

**Comment by vanbosse** [comment]
@geoidesic I'm not quite sure on the MAMP setup but, could it be it keeps port 8080 reserved for some reason? Have you tried changing the port the server listens to? That would be here: https://github.com/vanbosse/rabbitmq-demo/blob/master/js/server.js#L4 and here: https://github.com/vanbosse/rabbitmq-demo/blob/master/index.html#L16

**Comment by geoidesic** [comment]
Thanks but it's not working on any port. I've tried this now also on a vbox with CentOS installed with the ports opened and SELinux switched off. I get exactly the same error. 

I think the problem is the "localhost" bit. Once I changed it from localhost in index.html to the actual IP address of the vbox (10.0.0.100) then I got a step further... it is able to find this resource: 
```
http://10.0.0.100:8080/socket.io/socket.io.js, 
```
however the polling then fails:
```
http://localhost:8080/socket.io/?EIO=3&transport=polling&t=1420285534003-0
```
... which I expect is because it is once again trying to use localhost, instead of the IP address.

**Comment by geoidesic** [comment]
So I found there is a localhost setting in client.js also. I changed that to 10.0.0.100, which seems to have fixed the above problem. So now there are no 404 errors on resources, which is a step forward. However, the front-end is not receiving any updates.

**Comment by geoidesic** [comment]
RabbitMQ's logs are empty and the RabbitMQ server is started. The update.php script also contains a localhost but I think that one is correct as it must talk to RabbitMQ on the same server as the php script.

**Comment by geoidesic** [comment]
Fixed it!  
Last problem was that the dependencies (php-amqplib) were not included. There was no composer.json file so I assumed there were no dependencies. Once I'd correctly required the library and added the namespaces it works.

Hopefully this commentary helps someone else.

**Comment by vanbosse** [comment]
@geoidesic Great to see you got it fixed, bear in mind that this is just a demo, so more infrastructure/error checking/... will be very much welcome in production environments ;-)
